apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: minesweeper
  name: minesweeper
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: minesweeper
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: minesweeper
    spec:
      containers:
      - image: snaruto7/minesweeper:v1
        imagePullPolicy: IfNotPresent
        name: minesweeper