apiVersion: v1
kind: Service
metadata:
  labels:
    app: minesweeper
  name: minesweeper
  namespace: default
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app: minesweeper
  type: LoadBalancer

